new Property("spellcasting_class");
new Property("spellcasting_ability");
new RestrictInt(Property, "spell_save_dc");
new RestrictInt(Property, "spell_attack_bonus");

new RestrictInt(Property, "slots_lvl_1");
new Property("slots_expended_lvl_1");
new RestrictInt(Property, "slots_lvl_2");
new Property("slots_expended_lvl_2");
new RestrictInt(Property, "slots_lvl_3");
new Property("slots_expended_lvl_3");
new RestrictInt(Property, "slots_lvl_4");
new Property("slots_expended_lvl_4");
new RestrictInt(Property, "slots_lvl_5");
new Property("slots_expended_lvl_5");
new RestrictInt(Property, "slots_lvl_6");
new Property("slots_expended_lvl_6");
new RestrictInt(Property, "slots_lvl_7");
new Property("slots_expended_lvl_7");
new RestrictInt(Property, "slots_lvl_8");
new Property("slots_expended_lvl_8");
new RestrictInt(Property, "slots_lvl_9");
new Property("slots_expended_lvl_9");

new Property("cantrip_spell_1");
new Property("cantrip_spell_2");
new Property("cantrip_spell_3");
new Property("cantrip_spell_4");
new Property("cantrip_spell_5");
new Property("cantrip_spell_6");
new Property("cantrip_spell_7");
new Property("cantrip_spell_8");

new Property("lvl_1_spell_1");
new ToggleProperty("lvl_1_spell_prepared_1");
new Property("lvl_1_spell_2");
new ToggleProperty("lvl_1_spell_prepared_2");
new Property("lvl_1_spell_3");
new ToggleProperty("lvl_1_spell_prepared_3");
new Property("lvl_1_spell_4");
new ToggleProperty("lvl_1_spell_prepared_4");
new Property("lvl_1_spell_5");
new ToggleProperty("lvl_1_spell_prepared_5");
new Property("lvl_1_spell_6");
new ToggleProperty("lvl_1_spell_prepared_6");
new Property("lvl_1_spell_7");
new ToggleProperty("lvl_1_spell_prepared_7");
new Property("lvl_1_spell_8");
new ToggleProperty("lvl_1_spell_prepared_8");
new Property("lvl_1_spell_9");
new ToggleProperty("lvl_1_spell_prepared_9");
new Property("lvl_1_spell_10");
new ToggleProperty("lvl_1_spell_prepared_10");
new Property("lvl_1_spell_11");
new ToggleProperty("lvl_1_spell_prepared_11");
new Property("lvl_1_spell_12");
new ToggleProperty("lvl_1_spell_prepared_12");

new Property("lvl_2_spell_1");
new ToggleProperty("lvl_2_spell_prepared_1");
new Property("lvl_2_spell_2");
new ToggleProperty("lvl_2_spell_prepared_2");
new Property("lvl_2_spell_3");
new ToggleProperty("lvl_2_spell_prepared_3");
new Property("lvl_2_spell_4");
new ToggleProperty("lvl_2_spell_prepared_4");
new Property("lvl_2_spell_5");
new ToggleProperty("lvl_2_spell_prepared_5");
new Property("lvl_2_spell_6");
new ToggleProperty("lvl_2_spell_prepared_6");
new Property("lvl_2_spell_7");
new ToggleProperty("lvl_2_spell_prepared_7");
new Property("lvl_2_spell_8");
new ToggleProperty("lvl_2_spell_prepared_8");
new Property("lvl_2_spell_9");
new ToggleProperty("lvl_2_spell_prepared_9");
new Property("lvl_2_spell_10");
new ToggleProperty("lvl_2_spell_prepared_10");
new Property("lvl_2_spell_11");
new ToggleProperty("lvl_2_spell_prepared_11");
new Property("lvl_2_spell_12");
new ToggleProperty("lvl_2_spell_prepared_12");
new Property("lvl_2_spell_13");
new ToggleProperty("lvl_2_spell_prepared_13");

new Property("lvl_3_spell_1");
new ToggleProperty("lvl_3_spell_prepared_1");
new Property("lvl_3_spell_2");
new ToggleProperty("lvl_3_spell_prepared_2");
new Property("lvl_3_spell_3");
new ToggleProperty("lvl_3_spell_prepared_3");
new Property("lvl_3_spell_4");
new ToggleProperty("lvl_3_spell_prepared_4");
new Property("lvl_3_spell_5");
new ToggleProperty("lvl_3_spell_prepared_5");
new Property("lvl_3_spell_6");
new ToggleProperty("lvl_3_spell_prepared_6");
new Property("lvl_3_spell_7");
new ToggleProperty("lvl_3_spell_prepared_7");
new Property("lvl_3_spell_8");
new ToggleProperty("lvl_3_spell_prepared_8");
new Property("lvl_3_spell_9");
new ToggleProperty("lvl_3_spell_prepared_9");
new Property("lvl_3_spell_10");
new ToggleProperty("lvl_3_spell_prepared_10");
new Property("lvl_3_spell_11");
new ToggleProperty("lvl_3_spell_prepared_11");
new Property("lvl_3_spell_12");
new ToggleProperty("lvl_3_spell_prepared_12");
new Property("lvl_3_spell_13");
new ToggleProperty("lvl_3_spell_prepared_13");

new Property("lvl_4_spell_1");
new ToggleProperty("lvl_4_spell_prepared_1");
new Property("lvl_4_spell_2");
new ToggleProperty("lvl_4_spell_prepared_2");
new Property("lvl_4_spell_3");
new ToggleProperty("lvl_4_spell_prepared_3");
new Property("lvl_4_spell_4");
new ToggleProperty("lvl_4_spell_prepared_4");
new Property("lvl_4_spell_5");
new ToggleProperty("lvl_4_spell_prepared_5");
new Property("lvl_4_spell_6");
new ToggleProperty("lvl_4_spell_prepared_6");
new Property("lvl_4_spell_7");
new ToggleProperty("lvl_4_spell_prepared_7");
new Property("lvl_4_spell_8");
new ToggleProperty("lvl_4_spell_prepared_8");
new Property("lvl_4_spell_9");
new ToggleProperty("lvl_4_spell_prepared_9");
new Property("lvl_4_spell_10");
new ToggleProperty("lvl_4_spell_prepared_10");
new Property("lvl_4_spell_11");
new ToggleProperty("lvl_4_spell_prepared_11");
new Property("lvl_4_spell_12");
new ToggleProperty("lvl_4_spell_prepared_12");
new Property("lvl_4_spell_13");
new ToggleProperty("lvl_4_spell_prepared_13");

new Property("lvl_5_spell_1");
new ToggleProperty("lvl_5_spell_prepared_1");
new Property("lvl_5_spell_2");
new ToggleProperty("lvl_5_spell_prepared_2");
new Property("lvl_5_spell_3");
new ToggleProperty("lvl_5_spell_prepared_3");
new Property("lvl_5_spell_4");
new ToggleProperty("lvl_5_spell_prepared_4");
new Property("lvl_5_spell_5");
new ToggleProperty("lvl_5_spell_prepared_5");
new Property("lvl_5_spell_6");
new ToggleProperty("lvl_5_spell_prepared_6");
new Property("lvl_5_spell_7");
new ToggleProperty("lvl_5_spell_prepared_7");
new Property("lvl_5_spell_8");
new ToggleProperty("lvl_5_spell_prepared_8");
new Property("lvl_5_spell_9");
new ToggleProperty("lvl_5_spell_prepared_9");

new Property("lvl_6_spell_1");
new ToggleProperty("lvl_6_spell_prepared_1");
new Property("lvl_6_spell_2");
new ToggleProperty("lvl_6_spell_prepared_2");
new Property("lvl_6_spell_3");
new ToggleProperty("lvl_6_spell_prepared_3");
new Property("lvl_6_spell_4");
new ToggleProperty("lvl_6_spell_prepared_4");
new Property("lvl_6_spell_5");
new ToggleProperty("lvl_6_spell_prepared_5");
new Property("lvl_6_spell_6");
new ToggleProperty("lvl_6_spell_prepared_6");
new Property("lvl_6_spell_7");
new ToggleProperty("lvl_6_spell_prepared_7");
new Property("lvl_6_spell_8");
new ToggleProperty("lvl_6_spell_prepared_8");
new Property("lvl_6_spell_9");
new ToggleProperty("lvl_6_spell_prepared_9");

new Property("lvl_7_spell_1");
new ToggleProperty("lvl_7_spell_prepared_1");
new Property("lvl_7_spell_2");
new ToggleProperty("lvl_7_spell_prepared_2");
new Property("lvl_7_spell_3");
new ToggleProperty("lvl_7_spell_prepared_3");
new Property("lvl_7_spell_4");
new ToggleProperty("lvl_7_spell_prepared_4");
new Property("lvl_7_spell_5");
new ToggleProperty("lvl_7_spell_prepared_5");
new Property("lvl_7_spell_6");
new ToggleProperty("lvl_7_spell_prepared_6");
new Property("lvl_7_spell_7");
new ToggleProperty("lvl_7_spell_prepared_7");
new Property("lvl_7_spell_8");
new ToggleProperty("lvl_7_spell_prepared_8");
new Property("lvl_7_spell_9");
new ToggleProperty("lvl_7_spell_prepared_9");

new Property("lvl_8_spell_1");
new ToggleProperty("lvl_8_spell_prepared_1");
new Property("lvl_8_spell_2");
new ToggleProperty("lvl_8_spell_prepared_2");
new Property("lvl_8_spell_3");
new ToggleProperty("lvl_8_spell_prepared_3");
new Property("lvl_8_spell_4");
new ToggleProperty("lvl_8_spell_prepared_4");
new Property("lvl_8_spell_5");
new ToggleProperty("lvl_8_spell_prepared_5");
new Property("lvl_8_spell_6");
new ToggleProperty("lvl_8_spell_prepared_6");
new Property("lvl_8_spell_7");
new ToggleProperty("lvl_8_spell_prepared_7");

new Property("lvl_9_spell_1");
new ToggleProperty("lvl_9_spell_prepared_1");
new Property("lvl_9_spell_2");
new ToggleProperty("lvl_9_spell_prepared_2");
new Property("lvl_9_spell_3");
new ToggleProperty("lvl_9_spell_prepared_3");
new Property("lvl_9_spell_4");
new ToggleProperty("lvl_9_spell_prepared_4");
new Property("lvl_9_spell_5");
new ToggleProperty("lvl_9_spell_prepared_5");
new Property("lvl_9_spell_6");
new ToggleProperty("lvl_9_spell_prepared_6");
new Property("lvl_9_spell_7");
new ToggleProperty("lvl_9_spell_prepared_7");